- name: demo playbook
  hosts: all
  tasks:
    - name: Print hello world
      ansible.builtin.debug:
        msg: hello world
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
      when: ansible_default_ipv4.gateway is defined

 - name: Get uptime information
   ansible.builtin.shell: /usr/bin/uptime
   register: result